export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_SUCCESS";

export const CREATE_POST = "CREATE_POST";
export const DELETE_SINGLE_POST = "DELETE_SINGLE_POST";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const DELETE_SINGLE_COMMENT = "DELETE_SINGLE_COMMENT";
export const DELETE_ALL_COMMENT = "DELETE_ALL_COMMENT";
export const DELETE_ALL_POST = "DELETE_ALL_POST";